name = "ExploratoryFactorAnalysis"
uuid = "a03df6c4-44ce-4811-ae2a-076447e7d7c8"
authors = ["Xunjian-Li <11930699@mail.sustech.edu.cn> and contributors"]
version = "1.0.0-DEV"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.9"
Arpack = "0.5"
DataFrames = "1"
Distributions = "0.25"
KrylovKit = "0.10"
MultivariateStats = "0.10"
StatsBase = "0.34"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]





# name = "ExploratoryFactorAnalysis"
# uuid = "a03df6c4-44ce-4811-ae2a-076447e7d7c8"
# authors = ["Xunjian-Li <11930699@mail.sustech.edu.cn> and contributors"]
# version = "1.0.0-DEV"

# [deps]
# Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
# DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
# Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
# KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
# LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
# MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
# Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
# Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
# StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
# Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

# [compat]
# Arpack = "0.5.4"
# DataFrames = "1.8.1"
# Distributions = "0.25.122"
# KrylovKit = "0.10.2"
# LinearAlgebra = "1.11.0"
# MultivariateStats = "0.10.3"
# Printf = "1.11.0"
# Random = "1.11.0"
# StatsBase = "0.34.9"
# Test = "1.11.0"
# julia = "1.6"


# [extras]
# Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

# [targets]
# test = ["Test"]


